#!/bin/bash

echo "🔐 Google OAuth Setup Guide for Sports Platform"
echo "=============================================="
echo ""
echo "Follow these steps to set up Google OAuth credentials:"
echo ""
echo "1. 🌐 Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. 📁 Create or select your project:"
echo "   - Click 'Select a project' dropdown"
echo "   - Click 'New Project' if needed"
echo "   - Name: 'sports-platform' (or your preferred name)"
echo ""
echo "3. 🔧 Enable Google OAuth 2.0 API:"
echo "   - Go to 'APIs & Services' > 'Library'"
echo "   - Search for 'Google+ API' or 'Google Identity'"
echo "   - Enable the API"
echo ""
echo "4. 🔑 Create OAuth 2.0 Credentials:"
echo "   - Go to 'APIs & Services' > 'Credentials'"
echo "   - Click 'Create Credentials' > 'OAuth 2.0 Client IDs'"
echo "   - Application type: 'Web application'"
echo "   - Name: 'Sports Platform Development'"
echo ""
echo "5. 🌍 Configure Authorized URLs:"
echo "   Authorized JavaScript origins:"
echo "   - http://localhost:3001"
echo "   - http://localhost:4200 (for frontend)"
echo ""
echo "   Authorized redirect URIs:"
echo "   - http://localhost:3001/api/v1/auth/google/callback"
echo ""
echo "6. 💾 Download credentials and copy:"
echo "   - Client ID"
echo "   - Client Secret"
echo ""
echo "7. 🔐 Set environment variables (see next steps)"
echo ""
echo "Press Enter to continue to environment setup..."
read

echo ""
echo "🌍 Environment Variables Setup"
echo "=============================="
echo ""
echo "Create or update your .env file with these variables:"
echo ""
echo "# Google OAuth Configuration"
echo "GOOGLE_CLIENT_ID=your_client_id_here"
echo "GOOGLE_CLIENT_SECRET=your_client_secret_here"
echo "GOOGLE_REDIRECT_URI=http://localhost:3001/api/v1/auth/google/callback"
echo ""
echo "Replace 'your_client_id_here' and 'your_client_secret_here' with"
echo "the actual values from Google Cloud Console."
echo ""
echo "Would you like to:"
echo "1. Test with mock credentials first (for development)"
echo "2. Set up real credentials now"
echo "3. View current environment status"
echo ""
echo "Enter your choice (1, 2, or 3):"